trade-tariff/trade-tariff-admin

.env.development
.env.test
.gitignore
Gemfile
Gemfile.lock
app/helpers/service_helper.rb
app/views/layouts/application.html.erb
config/application.rb
config/initializers/her.rb
config/routes.rb
lib/faraday_middleware/service_urls.rb
lib/routing_filter/service_path_prefix_handler.rb
lib/trade_tariff_admin.rb
lib/trade_tariff_admin/service_chooser.rb
spec/helpers/service_helper_spec.rb
spec/lib/faraday_middleware/service_urls_spec.rb
spec/lib/service_chooser_spec.rb
spec/rails_helper.rb
spec/routing/service_path_prefix_handler_spec.rb

https://transformuk.atlassian.net/browse/HOTT-579
- This mechanism enables us to choose between different backends based on
on the path prefix. This is consistent with the approach to routing
taken in the frontend application previously.
- It's needed to make sure we can provide access to the HMRC team to update various aspects of the tariff on both services

Adds routing filter mechanism

---

.circleci/config.yml
config/initializers/cookies_serializer.rb

HOTT-<TODO>
- We want to be able to update the admin app in staging to manage updates/rollbacks

Adds staging deploy to circle ci workflow

---

app/models/rollback.rb
app/views/rollbacks/index.html.erb

[HOTT-1112](https://transformuk.atlassian.net/browse/HOTT-1112)
- We currently have rollbacks on Dev and Staging which are assigned to user accounts which no longer exist

HOTT-1112 Fix for rollbacks without users

---

spec/features/chapter_notes_spec.rb
spec/features/chapter_search_reference_spec.rb
spec/features/commodity_search_reference_spec.rb
spec/features/heading_search_reference_spec.rb
spec/features/rollbacks_spec.rb
spec/features/section_notes_spec.rb
spec/features/section_search_reference_spec.rb

???
- Drive by fix because I ran into this looking at why one of the synonyms forms didn't work

Avoid specs relying on element ids

---

app/views/synonyms/_shared_actions.html+govuk.erb
app/views/synonyms/chapters/headings/index.html+govuk.erb
app/views/synonyms/chapters/search_references/edit.html+govuk.erb
app/views/synonyms/chapters/search_references/index.html+govuk.erb
app/views/synonyms/chapters/search_references/new.html+govuk.erb
app/views/synonyms/commodities/search_references/edit.html+govuk.erb
app/views/synonyms/commodities/search_references/index.html+govuk.erb
app/views/synonyms/commodities/search_references/new.html+govuk.erb
app/views/synonyms/headings/commodities/index.html+govuk.erb
app/views/synonyms/headings/search_references/edit.html+govuk.erb
app/views/synonyms/headings/search_references/index.html+govuk.erb
app/views/synonyms/headings/search_references/new.html+govuk.erb
app/views/synonyms/imports/show.html+govuk.erb
app/views/synonyms/sections/chapters/index.html+govuk.erb
app/views/synonyms/sections/index.html+govuk.erb
app/views/synonyms/sections/search_references/edit.html+govuk.erb
app/views/synonyms/sections/search_references/index.html+govuk.erb
app/views/synonyms/sections/search_references/new.html+govuk.erb
config/locales/en.yml

Convert synonyms to GovUK [5 / 7]

---

app/views/layouts/application.html+govuk.erb
app/views/news_items/_form.html+govuk.erb
app/views/news_items/edit.html+govuk.erb
app/views/news_items/index.html+govuk.erb
app/views/news_items/new.html+govuk.erb
config/locales/en.yml

Convert news to GovUK [6 / 7]

---

app/helpers/govuk_helper.rb
app/views/application/_markdown_field.html.erb
app/webpacker/javascripts/jquery.autosize.js
app/webpacker/javascripts/markdown-preview.js
app/webpacker/packs/application.js
app/webpacker/packs/application.scss
package.json
spec/helpers/govuk_helper_spec.rb
yarn.lock

Adds a live preview markdown editor field [7 / 7]

---

.circleci/config.yml

HOTT-????
- Currently its not possible to check the app on staging after merging - by the point you are checking it is already deploying to production.

Require confirmation before deploying to production

---

app/controllers/govspeak_controller.rb
app/helpers/service_helper.rb
app/models/news_item.rb
app/views/news_items/_form.html+govuk.erb
app/views/news_items/_form.html.erb
spec/helpers/service_helper_spec.rb
spec/models/news_item_spec.rb
spec/requests/govspeak_controller_spec.rb
spec/support/shared_context/service_chooser.rb

[HOTT-1132](https://transformuk.atlassian.net/browse/HOTT-1132)
- We want a way to insert the Service name into news item content shown on the frontend

HOTT-1132 service tags

---

.circleci/config.yml
Dockerfile
config/initializers/raven.rb
lib/trade_tariff_admin/service_chooser.rb

https://transformuk.atlassian.net/browse/HOTT-1216
- This makes the admin app consistent with all of our other apps and means we can manage it more consistently - recently, for example, I couldn't bump ruby until buildpacks were available reflecting a different cadence of upgrades between our apps.

HOTT-1216: Dockerise admin app

---

.circleci/config.yml

https://transformuk.atlassian.net/browse/HOTT-1216
- This is required in order to kick off a staging and production deploy using the docker image
The rollout plan is to:
1. Rename staging app
2. Manually create staging app with a arbitrary docker image in manifest with the old name
3. Kick off ci process by merging this PR
4. Validate staging is up and running
5. Stop old renamed staging app
6. Validate staging is still up and running
7. Delete old renamed staging app
... repeat for production

HOTT-1216: Enable docker in staging and production

---

.circleci/config.yml

https://transformuk.atlassian.net/browse/HOTT-1216
- Reduce cognitive overhead when reviewing our ci config

HOTT-1216: Clean up after docker migration

---

.circleci/config.yml

[HOTT-1223](https://transformuk.atlassian.net/browse/HOTT-1223)
- We want to track when we have released to production
- We want to know what got released to production
- This is a step towards allowing re-deploying existing releases without requiring a full rebuild

HOTT-1223 Added CI step to generate release notes

---

app/models/commodity.rb
app/views/synonyms/headings/commodities/index.html.erb

https://transformuk.atlassian.net/browse/HOTT-1240
- This is no longer relevant since we can create search references for non 80 productline suffix commodities

HOTT-1240: Removes leaf from commodity api

---

.circleci/config.yml

HOTT-<TODO>
- Currently we are - and it wont work because we're not building the images - we don't want to be anyway

Fix for trying to deploy dependabot prs

---

.circleci/config.yml

[HOTT-1223](https://transformuk.atlassian.net/browse/HOTT-1223)
- It makes it easier to identify docker images which were released to production
The docker image is tagged _before_ the GitHub release is created - this seems back to front _but_ I'm planning to change the actual release to production to be triggered by an appropriately named git tag (which will allow for easy rollbacks from CI), since the creation of a GitHub release will create that tag, and that will trigger deployment of the docker image - it needs the docker tag to exist before the git tag is created to avoid a race condition in CI

HOTT-1223 Tagged docker images as production releases

---

.env.development
app/controllers/synonyms/exports_controller.rb
app/controllers/synonyms/search_references_controller.rb
app/models/chapter.rb
app/models/commodity.rb
app/models/commodity/search_reference.rb
app/models/heading.rb
app/models/section.rb
app/services/search_reference/import_service.rb
app/views/synonyms/headings/commodities/index.html.erb
spec/factories/commodity_factory.rb
spec/factories/search_reference_factory.rb
spec/factories/user_factory.rb
spec/models/chapter_spec.rb
spec/models/commodity/search_reference_spec.rb
spec/models/commodity_spec.rb
spec/models/heading_spec.rb
spec/models/section_spec.rb
spec/requests/synonyms/commodities/search_references_controller_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1248
- This is needed in order to differentiate between different commodity subheadings

HOTT-1248: Support productline_suffix in commodity search references

---

.circleci/config.yml

[HOTT-1241](https://transformuk.atlassian.net/browse/HOTT-1241)
- This will allow us to re-run the tagged release pipeline, there by giving us a rollback / re-deploy feature for our pipelines
- The reworking of the slack notification step is because now the pipeline is split up with the second being triggered by the tag, they no longer share a workspace so can no longer share files
- May potentially break production deploys but should fail rather then resulting in outage. Has been tested (via pipeline hacking) in dev space but final 'production' pipeline can only be tested after merge.

HOTT-1241 Add rollback

---

.circleci/config.yml

[HOTT-1241](https://transformuk.atlassian.net/browse/HOTT-1241)
- We want to deploy release tagged docker images, this change will facilitate using release tags in production but continuing to use SHA derived tags in staging and development
- Changes production deployment pipeline, follows same pattern as dev and staging so problems should show up at those stages

HOTT-1241 Explicitly specify docker tag to deploy

---

.circleci/config.yml

[HOTT-1223](https://transformuk.atlassian.net/browse/HOTT-1223)
[Release 20220117-1446](https://github.com/trade-tariff/trade-tariff-admin/releases/tag/release-20220117-1446) ended up with with the fallback release notes, incorrectly. 
It turns out `wc -l` counts explicit line endings, not lines. Because the last line of git log output lacks a new line (or bash is stripping it when writing to a file) this means wc -l is returning the real line count - 1.
Which means if there was only a single PR merged, and so a single line then this will be read as 0 lines, ie blank release notes and the fallback release notes will be created.
Solution is to just rely on bash' ability to detect empty files.

HOTT-1223 Fixed detection of empty release notes

---

.circleci/config.yml

HOTT-???
- We're defining how to download and retrieve the cf command in multiple places - this removes the duplication

Split cf install into separate command for reuse

---

.circleci/config.yml

[HOTT-1206](https://transformuk.atlassian.net/browse/HOTT-1206)
- CI does not queue and concurrent downloads can result in the deletion of the server being deployed to

HOTT-1206 Added queuing to deploy step in CI

---

app/models/commodity.rb
app/views/synonyms/headings/commodities/index.html.erb

HOTT-<TODO>
- Required for understanding what type of search reference is going to be created

Surface whether a commodity is declarable

---

.circleci/config.yml

[HOTT-1328](https://transformuk.atlassian.net/browse/HOTT-1328)
- We have to use env vars for the slack orb and escaping properly seems impossible - this corrects removal of escaped quotes

HOTT-1328 Fixed stripping quotes in release notes

---

.circleci/config.yml

[HOTT-1351](https://transformuk.atlassian.net/browse/HOTT-1351)
- We want to share this code with our other projects

HOTT-1351 Use orb to generate + publish release notes

---

.rspec
Gemfile.lock
app/helpers/service_helper.rb
app/models/tariff_update.rb
app/views/tariff_updates/_actions.html.erb
app/views/tariff_updates/index.html.erb
config/locales/en.yml
spec/factories/tariff_update_factory.rb
spec/features/tariff_updates_spec.rb
spec/helpers/service_helper_spec.rb
spec/models/tariff_update_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1364
- The UI isn't particularly up-to-date and the inserts give us a lot more information about what was imported in each update

HOTT-1364: Surface oplog inserts in the admin UI

---

app/views/tariff_updates/_actions.html.erb

https://transformuk.atlassian.net/browse/HOTT-1388
- This is so that we can easily see which filename is being downloaded for which day

HOTT-1388: Show filename when downloading current file

---

.circleci/config.yml

This allows a developer to create a release, and check the release notes prior to rolling it out
And removes the risk of accidentally releasing and older release to prod

Add a second confirmation step

---

app/controllers/govspeak_controller.rb
app/controllers/news_items_controller.rb
app/helpers/news_items_helper.rb
app/helpers/service_helper.rb
app/models/govspeak_preview.rb
app/models/news_item.rb
app/views/news_items/_form.html.erb
app/views/news_items/index.html.erb
config/initializers/govspeak_sanitizer.rb
config/locales/en.yml
spec/factories/news_item_factory.rb
spec/helpers/news_items_helper_spec.rb
spec/helpers/service_helper_spec.rb
spec/models/govspeak_preview_spec.rb
spec/models/news_item_spec.rb
spec/requests/govspeak_controller_spec.rb

[HOTT-1381](https://transformuk.atlassian.net/browse/HOTT-1381)
- We want to edit the header banner on the frontend from the admin area

HOTT-1381 Add banner news items

---

.circleci/config.yml

HOTT-???
During yesterdays rollback we wanted to test the rollback on Staging before deploying to Production. I'm doing this in the Admin because this is my testbed for this process.
In the normal 'click to release' process, this wont change anything - it will redeploy the same Git Sha to staging as is already there, but using the tagged release image, instead of the git sha image.
In a rollback or re-release scenario this creates the opportunity to check what we are about to rollback to on Staging before we deploy it to production
Note: This occurs concurrently with the production deploy so whether to wait for it to complete is up to the developer, they're not held up by it for an urgent rollback

Deploy tag to staging when creating release

---

.circleci/config.yml

HOTT-???
- I can't find away of making it queue against 'main' and the chance of a collision is low, and worst case its only staging that fails to deploy

Fix for deploying tag to staging

---

.circleci/config.yml
.rubocop.yml
app/controllers/synonyms/search_references_controller.rb
app/helpers/govuk_helper.rb
app/services/search_reference/export_all_service.rb
spec/features/chapter_search_reference_spec.rb
spec/features/commodity_search_reference_spec.rb
spec/features/heading_search_reference_spec.rb
spec/features/section_search_reference_spec.rb
spec/models/tariff_update_spec.rb

HOTT-????
- Brakeman is more important than utilising Ruby 3.1 hash syntax
- its trivial to convert back at a future point
- for now it reduces noise in PRs because rubocop isn't insisting on an syntax change to existing code

Match rubocop requirements to brakemans

---

.rubocop.yml
Gemfile.lock
app/controllers/synonyms/search_references_controller.rb
app/helpers/govuk_helper.rb
app/services/search_reference/export_all_service.rb
spec/features/chapter_search_reference_spec.rb
spec/features/commodity_search_reference_spec.rb
spec/features/heading_search_reference_spec.rb
spec/features/section_search_reference_spec.rb
spec/models/tariff_update_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1478
- Brakeman now supports ruby 3.1.x syntax

HOTT-1478: Bump brakeman and tweak rubocop rules

---

.circleci/config.yml

[HOTT-1496](https://transformuk.atlassian.net/browse/HOTT-1496)
- our CLI usage seems to be incompatible with the newly released v2

HOTT-1496 Fix usage of sentry-cli

---

app/views/synonyms/chapters/headings/index.html.erb
app/views/synonyms/headings/commodities/index.html.erb
app/views/synonyms/sections/chapters/index.html.erb

HOTT-1555
- I'd misread the ticket

HOTT-1555 Corrected column headings for search references

---

spec/models/news_item_spec.rb
spec/rails_helper.rb
spec/requests/govspeak_controller_spec.rb
spec/requests/news_items_controller_spec.rb
spec/views/news_items/_form.html.erb_spec.rb
spec/views/news_items/index.html.erb_spec.rb

HOTT-<TODO>
- This is consistent with the rails generators and it is generally more desirable to do things in one way, only: https://github.com/rspec/rspec-rails/commit/ca0d249858903949052e06884e8e7f9d596cdc79

Disable RSpec dsl in main

---

Gemfile
Gemfile.lock

[HOTT-1567](https://transformuk.atlassian.net/browse/HOTT-1567)
Remove Gem redis-activesupport.
No need to change cache_store type, it is already using `:redis_cache_store`.
the gem redis-activesupport is not maintained, and it is unnecessary.

HOTT-1567: Remove Gem redis-activesupport.

---

app/views/synonyms/chapters/headings/index.html.erb

[HOTT-1634](https://transformuk.atlassian.net/browse/HOTT-1634)
- I typo'd my original search and replace

HOTT-1634 Fixed typo

---

app/controllers/tariff_updates_controller.rb
app/models/tariff_update.rb
app/models/tariff_update/inserts.rb
app/views/tariff_updates/index.html.erb
app/views/tariff_updates/show.html.erb
config/brakeman.ignore
config/routes.rb
spec/factories/tariff_update_factory.rb
spec/models/tariff_update/inserts_spec.rb
spec/models/tariff_update_spec.rb

https://transformuk.atlassian.net/browse/HOTT-1585
- This is much easier to review than the old method and supports richer data that was recently added, here: https://github.com/trade-tariff/trade-tariff-backend/pull/604

HOTT-1585: Add new tariff updates show page

---

Gemfile
Gemfile.lock
config/initializers/raven.rb
config/initializers/sentry.rb

HOTT-2006
- sentry-ruby is no longer supported
- Changes error reporting behaviour

HOTT-2006 convert to sentry rails

---

app/controllers/news_items_controller.rb
app/models/news/collection.rb
app/models/news/item.rb
app/views/news_items/_form.html.erb
app/views/news_items/edit.html.erb
app/views/news_items/new.html.erb
config/locales/en.yml
spec/factories/news/collection_factory.rb
spec/factories/news/item_factory.rb
spec/models/news/collection_spec.rb
spec/models/news/item_spec.rb
spec/requests/news_items_controller_spec.rb
spec/views/news_items/_form.html.erb_spec.rb

HOTT-2130
- We want to be able to edit the new fields from the admin area
- Low, admin area

HOTT-2130 add new news item fields

---

app/views/quotas/new.html.erb

HOTT-????
- It is confusing
- It is caused by both `govuk_form_helper` and the html page each rendering their own error summary

Avoid double error messages on quota search

---

app/models/news/item.rb
app/views/kaminari/_first_page.html.erb
app/views/kaminari/_gap.html.erb
app/views/kaminari/_last_page.html.erb
app/views/kaminari/_next_page.html.erb
app/views/kaminari/_page.html.erb
app/views/kaminari/_paginator.html.erb
app/views/kaminari/_prev_page.html.erb
app/views/news_items/index.html.erb
config/initializers/kaminari_config.rb
spec/support/api_responses_helper.rb
spec/views/news_items/index.html.erb_spec.rb

HOTT-2312
- The api _is_ paginated so this meant users could only edit stories from the first page
- None

HOTT-2312 Use pagination for news items

---

app/models/chapter_note.rb
app/models/news/item.rb
app/models/section_note.rb
app/views/application/_markdown_field.html.erb
spec/helpers/govuk_helper_spec.rb
spec/models/news/item_spec.rb

HOTT-2242
- It currently shows the content preview for the precis field

HOTT-2242 Fixed preview of news precis field

---

app/controllers/quotas_controller.rb
app/views/layouts/application.html.erb
app/views/quotas/new.html.erb
app/views/quotas/search.html.erb
config/routes.rb
spec/requests/quotas_controller_spec.rb

[HOTT-<TODO>](https://transformuk.atlassian.net/browse/HOTT-2226)
- The quota search page was displaying as a "new quota" page and misleading users

HOTT-2226: Fixed quota search URL and removed back button

---

app/models/tariff_update/inserts.rb
app/views/tariff_updates/show.html.erb
spec/factories/tariff_update_factory.rb
spec/models/tariff_update/inserts_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2465
With some skipped events:
With no skipped events:
- This is new functionality that it would be great to be able to review

HOTT-2465: Adds transfer events skipped ui

---

app/views/quotas/_balance_events.html.erb
app/webpacker/packs/application.scss
spec/views/quotas/_balance_events.html.erb_spec.rb

[HOTT-<2808>](https://transformuk.atlassian.net/browse/HOTT-2808)
- This provides a better user experience for Admin users

HOTT-2808: Quota definitions sort order, thousands separator and CSS changes

---

app/helpers/quotas_helper.rb
app/models/quota_order_numbers/measurement_unit.rb
app/models/quota_order_numbers/quota_definition.rb
app/views/quotas/_balance_events.html.erb
app/views/quotas/_balance_events_chart.html.erb
app/views/quotas/_quota_definition.html.erb
app/views/quotas/show.html.erb
spec/factories/measurement_unit_factory.rb
spec/factories/quota_definition_factory.rb
spec/helpers/quotas_helper_spec.rb
spec/models/quota_order_numbers/quota_definition_spec.rb
spec/views/quotas/_quota_definition.html.erb_spec.rb
spec/views/quotas/show.html.erb_spec.rb

https://transformuk.atlassian.net/browse/HOTT-2980
- This was kicked off by the fact that Matt noticed that certain quota order numbers had definition tables that showed the wrong measurement unit

HOTT-2980: Quota UI enhancements and bug fixes

---

config/environments/production.rb

- Ignored `checkz` action of the healthcheck controller in lograge options.
- We don't need this to be logged in production mode, it's just noise.

BAU: Don't log healthchecks in production

---

app/controllers/references/search_references_controller.rb
spec/factories/chapter_factory.rb
spec/factories/commodity_factory.rb
spec/factories/heading_factory.rb
spec/features/commodity_search_reference_spec.rb

https://transformuk.atlassian.net/browse/HOTT-4238
- This value is used to uniquely identify commodity search references when listing and creating them.
- This handles the fact that subheadings/commodities are managed under the same controller in the admin apis

HOTT-4238: Fix issue with unset producline suffix value

---

bin/webpack

HOTT-4301
- Webpacker requires webpack v4
- Webpack v4 needs MD4
- OpenSSL 3 hides MD4 behind a config option
- Setting it via `.env` files works for specs but not for dynamic compilation via `rails s` or via `rails webpacker:compile` - because the env files are loaded during app initialization and the app is seems not to be initialized for the webpacker process
- None, only affects `bin/webpack` binary

HOTT-4301 set NODE_OPTIONS for webpack compilation

---

.circleci/config.yml

[HOTT-2793](https://transformuk.atlassian.net/browse/HOTT-2793)
- Removed deploy jobs to dev/staging in PaaS
- Maintaining two services increases complexity
- PaaS needs to be decommissioned 
- Our dev and staging URLs point to the new service

HOTT-2793: Stop Deploying to PaaS for Dev/Staging

---

config/initializers/session_store.rb

[HOTT-4437](https://transformuk.atlassian.net/browse/HOTT-4437)
- Set `secure` on the session store cookie when `Rails.env` is `production`.
- This was identified in the security review.

HOTT-4437: Set Secure Flag on Cookies

---

.circleci/config.yml

- Fixed broken `image-name` parameter in release job
- It's wrong and blocking releases

BAU: Fix image-name parameter in production release job

---

app/views/references/_shared_actions.html.erb

https://transformuk.atlassian.net/browse/HOTT-4865
Change link_to to button_to to use the POST method.
Also, it is a bad practice to use links to make POST calls.

Fix 'export all search references' button

---

app/models/subheading.rb

This PR fixes:
NameError uninitialized constant Subheading (NameError)
which is caused by "constantize" a "subheading" string. The error is present in Sentry, and it started 4 months ago.
https://engine-le.sentry.io/issues/4538644179/?project=5738286&query=release%3A08416c1&referrer=release-issue-stream
https://transformuk.atlassian.net/browse/HOTT-4865
I am doing this to fix the bug.

Fix: NameError uninitialized constant Subheading

---

.pre-commit-config.yaml
terraform/README.md
terraform/main.tf

[HOTT-5060](https://transformuk.atlassian.net/browse/HOTT-5060)
- Added an init container
- We need to make sure the migrations run when the app starts

HOTT-5060: Run database migrations in an init container

---

app/controllers/green_lanes/category_assessments_controller.rb
app/models/green_lanes/category_assessment.rb
app/views/green_lanes/category_assessments/index.html.erb
app/views/layouts/application.html.erb
config/initializers/exceptions.rb
config/initializers/her.rb
config/routes.rb
spec/factories/green_lanes/category_assessment_factory.rb
spec/models/green_lanes/category_assessment_spec.rb
spec/requests/green_lanes/category_assessments_controller_spec.rb

[GL-106](https://transformuk.atlassian.net/browse/GL-106)
- We can see what is in the category assessments table and manage them
-
-

GL-106: Add Admin screen to list out all category assessments

---

app/controllers/green_lanes/category_assessments_controller.rb
app/views/green_lanes/category_assessments/edit.html.erb
config/routes.rb
spec/requests/green_lanes/category_assessments_controller_spec.rb

[GL-109](https://transformuk.atlassian.net/browse/GL-109)
- So that we can keep the category assessment data up to date

GL-109: Add deletion of Category Assessments

---

app/controllers/green_lanes/category_assessments_controller.rb
app/models/green_lanes/theme.rb
app/views/green_lanes/category_assessments/edit.html.erb
app/views/green_lanes/category_assessments/index.html.erb
config/routes.rb
spec/requests/green_lanes/category_assessments_controller_spec.rb

[GL-108](https://transformuk.atlassian.net/browse/GL-108)
- So that we can maintain the list of valid category assessments

GL-108: Add Edit screens for Category Assessments

---

app/controllers/green_lanes/exempting_certificate_overrides_controller.rb
app/views/green_lanes/exempting_certificate_overrides/index.html.erb
spec/requests/green_lanes/exempting_certificate_overrides_controller_spec.rb

[GL-458](https://transformuk.atlassian.net/browse/GL-458)
- Admin user should be able to manage exemption certificate overrides

GL-458: Add admin UI to remove overrides

---

app/controllers/green_lanes/exemptions_controller.rb
spec/requests/green_lanes/exemptions_controller_spec.rb

[GL-495](https://transformuk.atlassian.net/browse/GL-495)
- Admin user should be able to manage exemption

GL-495: Add admin UI to remove pseudo exemptions

---

app/controllers/concerns/xi_only.rb
app/controllers/green_lanes/category_assessments_controller.rb
app/controllers/green_lanes/exempting_certificate_overrides_controller.rb
app/controllers/green_lanes/exemptions_controller.rb
app/models/green_lanes/exemption.rb
app/views/green_lanes/exemption/index.html.erb
app/views/green_lanes/exemptions/_form.html.erb
app/views/green_lanes/exemptions/edit.html.erb
app/views/green_lanes/exemptions/index.html.erb
app/views/green_lanes/exemptions/new.html.erb
app/views/layouts/application.html.erb
config/routes.rb
spec/factories/green_lanes/exemption_factory.rb
spec/requests/green_lanes/exemptions_controller_spec.rb

HOTT-<TODO>
- Admin user should be able to manage exemption

GL-382: Exemption list UI

---

app/controllers/green_lanes/category_assessments_controller.rb
app/controllers/green_lanes/measures_controller.rb
app/models/green_lanes/category_assessment_exemption.rb
app/models/green_lanes/measure.rb
app/views/green_lanes/category_assessments/_exemptions.html.erb
app/views/green_lanes/category_assessments/_measure_form.html.erb
app/views/green_lanes/category_assessments/_measures.html.erb
app/views/green_lanes/category_assessments/index.html.erb
app/views/green_lanes/measures/index.html.erb
config/routes.rb
spec/factories/green_lanes/category_assessment_factory.rb
spec/factories/green_lanes/measure_factory.rb
spec/requests/green_lanes/category_assessments_controller_spec.rb
spec/requests/green_lanes/measures_controller_spec.rb

[GL-384](https://transformuk.atlassian.net/browse/GL-384)
- Admin user should be able to manage GL measures

GL-384: Add deleting pseudo measures

---

app/controllers/green_lanes/category_assessments_controller.rb
app/models/green_lanes/category_assessment.rb
app/models/green_lanes/measure_pagination.rb
app/views/green_lanes/category_assessments/_measures.html.erb
app/views/green_lanes/exempting_additional_code_overrides/new.html.erb
app/views/green_lanes/exempting_certificate_overrides/new.html.erb
spec/factories/green_lanes/category_assessment_factory.rb
spec/factories/green_lanes/measure_pagination_factory.rb
spec/requests/green_lanes/category_assessments_controller_spec.rb

[GL-735](https://transformuk.atlassian.net/browse/GL-735)
- Number of measure records cannot be handle without pagination

GL-735: Admin UI: Paginate pseudo measures in CA edit page

---

app/controllers/concerns/sortable.rb
app/controllers/green_lanes/category_assessments_controller.rb
app/helpers/application_helper.rb
app/views/green_lanes/category_assessments/index.html.erb
spec/requests/green_lanes/category_assessments_controller_spec.rb

[GL-1065](https://transformuk.atlassian.net/browse/GL-1065)
- User needs to sort the result table by different attributes

GL-1065: Implement Sorting Functionality on Category Assessments Page

---

app/controllers/green_lanes/category_assessments_controller.rb
app/views/green_lanes/category_assessments/index.html.erb
app/webpacker/packs/application.scss

[HMRC-142](https://transformuk.atlassian.net/browse/HMRC-142)
- Admin users need to filter the CA list by these fields

HMRC-142: Implement Filtering Options on Category Assessments Page

---

terraform/locals.tf

HMRC-683
Historically `backend-admin-uk/xi` had a read-write connection to the database, and `backend-uk/xi` was read-only.  For a while now `backend` has had read/write making the extra `backend-admin` deployments unnecessary.
This PR points the admin straight at the regular backend.
Requires https://github.com/trade-tariff/trade-tariff-backend/pull/2117

HMRC-683 Repoint to central backend

---

.env.development
app/controllers/authenticated_controller.rb
app/controllers/basic_sessions_controller.rb
app/models/basic_session.rb
app/views/basic_sessions/new.html.erb
config/locales/en.yml
config/routes.rb
lib/trade_tariff_admin.rb

[HMRC-941](https://transformuk.atlassian.net/browse/HMRC-941)
The plan is that:
1. local development, the development and staging aws-hosted apps will use this
2. production will use SSO using the signonotron2 app that GDS host (for now)

HMRC-941: Adds simple authentication scheme

---

.github/workflows/deploy-to-development.yml
.github/workflows/deploy-to-production.yml
.github/workflows/deploy-to-staging.yml
Gemfile
Gemfile.lock
spec/rails_helper.rb

[HMRC-941](https://transformuk.atlassian.net/browse/HMRC-941)
- This is needed since we're now testing the admin apps in e2e tests

HMRC-941: Support admin validations in e2e tests

---

.github/workflows/deploy-to-production.yml

[HMRC-950](https://transformuk.atlassian.net/browse/HMRC-950)
- This enables automatic deploys to production behind the new admin specs

HMRC-950: Enables continuous deployments of the admin application

---

app/controllers/authenticated_controller.rb
app/controllers/concerns/basic_session_auth.rb
app/controllers/concerns/sso_auth.rb
app/policies/rollback_policy.rb
config/initializers/secret_token.rb
spec/features/rollbacks_spec.rb
spec/requests/news_collections_controller_spec.rb
spec/requests/news_items_controller_spec.rb
spec/trade_tariff_admin/service_chooser_spec.rb

BAU
- This is required to fix certain operations that expect a hydrated user model

BAU: Refactor auth types into concern and add `current_user`

---

app/webpacker/javascripts/markdown-preview.js

[HMRC-956](https://transformuk.atlassian.net/browse/HMRC-956)
- This is needed to make sure we can safely preview content

HMRC-956: Fixes bug in preview since we enabled protect_from_forgery with: :exception

---

.github/workflows/deploy-to-production.yml

[HOTT-962](https://transformuk.atlassian.net/browse/HMRC-962)
- When deploying to production, we’re notifying in production alerts

HMRC-962: Notify in production-alerts

---

app/controllers/news_items_controller.rb
app/models/news/item.rb
app/views/news_items/_form.html.erb
spec/factories/news/item_factory.rb
spec/models/news/item_spec.rb

[HOTT-1067](https://transformuk.atlassian.net/browse/HMRC-1067)
I have added notify subscribers to news item
- Admin news items can be checked or unchecked to notify subscribers of stop press updates

HMRC-1067 Add Notify Subscribers To News Item 

---

.github/pull_request_template.md
app/controllers/news_collections_controller.rb
app/models/news/collection.rb
app/views/news_collections/_form.html.erb
app/views/news_collections/index.html.erb
spec/factories/news/collection_factory.rb
spec/models/news/collection_spec.rb
spec/views/news_collections/_form.html.erb_spec.rb

HOTT-1074
- Added a new attribute for news collections
- Which news items are sent to subscribers needs to be limited to certain types of news item.

Add subscribable attribute

---

app/views/references/chapters/search_references/index.html.erb
app/views/references/commodities/search_references/index.html.erb
app/views/references/headings/search_references/index.html.erb

[HMRC-1068](https://transformuk.atlassian.net/browse/HMRC-1068)
- It's not been used and built using non-json-api compliant x-meta header

HMRC-1068: HMRC-1068: Kill the totally non-json-api compliant x-meta in pagination - some changes left uncommited

---

app/controllers/quotas_controller.rb
app/models/quota_search.rb
app/views/quotas/new.html.erb
config/initializers/attribute_types.rb
config/locales/en.yml
lib/active_model_types/tariff_date.rb
spec/models/quota_search_spec.rb
spec/requests/quotas_controller_spec.rb

[HMRC-1379](https://transformuk.atlassian.net/browse/HMRC-1379)
- This is needed to pick a version of an order number and avoid confusion

HMRC-1379: Adds support for as of to quota search

---

app/views/live_issues/_form.html.erb

[PRDEX-71](https://transformuk.atlassian.net/browse/PRDEX-71)
- We should hint admin users how to use the live issues form

PRDEX-71 | Update wording for commodities in new live issue

---

Gemfile
app/models/green_lanes/update_notification.rb
app/views/green_lanes/update_notifications/index.html.erb
config/application.rb
config/brakeman.ignore

[HMRC-1479](https://transformuk.atlassian.net/browse/HMRC-1479)
- This is required to make sure that HMRC has as much context as possible and reflects that some updated measure types actually aren't present in the database despite being referenced by the generated notification

HMRC-1479: Handle measure type and role presentation
