app/controllers/application_controller.rb, app/controllers/rollbacks_controller.rb, app/controllers/synonyms/search_references_controller.rb, app/models/chapter_note.rb, app/models/rollback.rb, app/models/section_note.rb, app/services/search_reference/export_service.rb, app/services/search_reference/import_service.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, config/initializers/current_release_sha.rb, config/initializers/gds-sso.rb, config/initializers/her.rb, config/initializers/raven.rb, config/initializers/shrine.rb, config/initializers/sidekiq.rb, config/initializers/simple_form_bootstrap.rb, config/routes.rb, lib/her/middleware/accept_api_v2.rb, lib/redis_resolver.rb, lib/trade_tariff_admin.rb
HOTT-<TODO>
- Bump kramdown from 2.3.0 to 2.3.1
- Updates rubocop standards
- Auto lint spec files
- Fix Style/StringLiterals infractions
=> Rubocop continuedd

Rakefile, app/controllers/notes/chapters_controller.rb, app/controllers/synonyms/chapters/search_references_controller.rb, app/controllers/synonyms/commodities/search_references_controller.rb, app/controllers/synonyms/headings/search_references_controller.rb, app/controllers/synonyms/search_references_controller.rb, app/controllers/synonyms/sections/search_references_controller.rb, app/helpers/application_helper.rb, app/helpers/search_references_helper.rb, app/jobs/import_search_references_job.rb, app/models/chapter/search_reference.rb, app/models/commodity/search_reference.rb, app/models/concerns/her_paginatable.rb, app/models/heading/search_reference.rb, app/models/import_task.rb, app/models/search_reference.rb, app/models/section/search_reference.rb, app/policies/chapter_note_policy.rb, app/policies/search_reference_policy.rb, app/policies/section_note_policy.rb, app/services/search_reference/export_service.rb, app/services/search_reference/import_service.rb, config.ru, config/application.rb, config/environments/production.rb, config/initializers/current_release_sha.rb, config/initializers/simple_form_bootstrap.rb, config/routes.rb, lib/gds_editor_constraint.rb, lib/redis_resolver.rb
=> More rubocop

.circleci/config.yml, .gitignore
HOTT-667
- We want to bring this application under CI 
- Validated any auth changes don't break the apps integration with the backend
=> Enable CI tests and deployment to Dev environment

.circleci/config.yml
HOTT-667
- Complete the workflow to deploy to master.
-
=> Hott 667 prod deploy

.circleci/config.yml, Gemfile
HOTT-679
- we want to have a security static analysis of our code.
-
-
- Validated any auth changes don't break the apps integration with the backend
=> HOTT-679 Add Brakeman to CI

spec/controllers/healthcheck_controller_spec.rb, spec/features/chapter_notes_spec.rb, spec/features/chapter_search_reference_spec.rb, spec/features/commodity_search_reference_spec.rb, spec/features/footnote_spec.rb, spec/features/heading_search_reference_spec.rb, spec/features/measure_types_spec.rb, spec/features/rollbacks_spec.rb, spec/features/section_notes_spec.rb, spec/features/section_search_reference_spec.rb, spec/features/tariff_updates_spec.rb, spec/helpers/service_helper_spec.rb, spec/lib/faraday_middleware/service_urls_spec.rb, spec/lib/service_chooser_spec.rb, spec/models/user_spec.rb, spec/policies/chapter_note_policy_spec.rb, spec/policies/section_note_policy_spec.rb, spec/routing/service_path_prefix_handler_spec.rb
HOTT-<TODO>
-
-
-
- Validated any auth changes don't break the apps integration with the backend
=> Make RSpec.describe consistent

.gitignore, app/controllers/notes/chapters/chapter_notes_controller.rb, app/controllers/notes/sections/section_notes_controller.rb, app/controllers/rollbacks_controller.rb, app/controllers/synonyms/search_references_controller.rb, app/models/rollback.rb, app/views/notes/chapters/chapter_notes/_fields.html.erb, app/views/notes/chapters/chapter_notes/edit.html.erb, app/views/notes/chapters/chapter_notes/new.html.erb, app/views/notes/sections/section_notes/_fields.html.erb, app/views/notes/sections/section_notes/edit.html.erb, app/views/notes/sections/section_notes/new.html.erb, app/views/rollbacks/new.html.erb, app/views/synonyms/chapters/search_references/edit.html.erb, app/views/synonyms/chapters/search_references/new.html.erb, app/views/synonyms/commodities/search_references/edit.html.erb, app/views/synonyms/commodities/search_references/new.html.erb, app/views/synonyms/headings/search_references/edit.html.erb, app/views/synonyms/headings/search_references/new.html.erb, app/views/synonyms/sections/search_references/edit.html.erb, app/views/synonyms/sections/search_references/new.html.erb, config/initializers/simple_form_bootstrap.rb, spec/features/rollbacks_spec.rb
[HOTT-1032](https://transformuk.atlassian.net/browse/HOTT-1032)
- We want to be able to easily update the admin area
=> HOTT-1032: fix form builder

.circleci/config.yml, CONTRIBUTING.md
https://transformuk.atlassian.net/browse/HOTT-1091
=> Remove master references

.circleci/config.yml, .gitignore, Gemfile, Gemfile.lock, app/webpacker/packs/application.js, app/webpacker/packs/application.scss, bin/webpack, bin/webpack-dev-server, config/webpack/development.js, config/webpack/environment.js, config/webpack/production.js, config/webpack/test.js, config/webpacker.yml, package.json, postcss.config.js, yarn.lock
=> Add webpacker [1 / 7]

.circleci/config.yml, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/helpers/application_helper.rb, app/views/kaminari/_first_page.html+govuk.erb, app/views/kaminari/_gap.html+govuk.erb, app/views/kaminari/_last_page.html+govuk.erb, app/views/kaminari/_next_page.html+govuk.erb, app/views/kaminari/_page.html+govuk.erb, app/views/kaminari/_paginator.html+govuk.erb, app/views/kaminari/_prev_page.html+govuk.erb, app/views/layouts/application.html+govuk.erb, app/webpacker/packs/application.js, app/webpacker/packs/application.scss, lib/trade_tariff_admin.rb
=> Add GovUK frontend [2 / 7]

app/helpers/application_helper.rb, app/helpers/service_helper.rb, app/views/application/_auth_banner.html.erb, app/views/application/_flashes.html+govuk.erb, app/views/layouts/application.html+govuk.erb, app/views/synonyms/_shared_actions.html+govuk.erb, app/views/synonyms/sections/chapters/index.html+govuk.erb, app/webpacker/packs/application.scss, lib/trade_tariff_admin/service_chooser.rb, spec/helpers/application_helper_spec.rb, spec/helpers/service_helper_spec.rb
=> Frontend functionality [3 / 7]

.circleci/config.yml
[HOTT-1223](https://transformuk.atlassian.net/browse/HOTT-1223)
- So we have visibility across the team when a release rolls out
=> HOTT-1223 Notify slack channel of release

Dockerfile, Gemfile, Gemfile.lock, config/initializers/assets.rb
We don't need it and it massively slows down admin builds
=> Drop asset pipeline 

.circleci/config.yml
[HOTT-1350](https://transformuk.atlassian.net/browse/HOTT-1350)
- We want to share this code with the other repos
=> HOTT-1350 Use private orb

app/models/tariff_update/inserts.rb, app/views/tariff_updates/show.html.erb, spec/factories/tariff_update_factory.rb, spec/models/tariff_update/inserts_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1661
- This is required to display newly stored missing entities if there are any
=> HOTT-1585: Adds UI for missing inserts

app/views/tariff_updates/show.html.erb
=> HOTT-1585: Fix missing details

.rubocop.yml
=> Lint frozen string literal

config/puma.rb
HOTT-<TODO>
- Puma 6 removed the default config.ru configuration module
=> Fixes issue with puma 6

app/controllers/quotas_controller.rb, app/models/quota_search.rb, app/views/layouts/application.html.erb, app/views/quotas/search.html.erb, app/views/quotas/search_results.html.erb, config/locales/en.yml, config/routes.rb
https://transformuk.atlassian.net/browse/HOTT-1529
add new form to search quotas
To implement quota search.
=> HOTT-1529: Add routing/controller/form for quota search page.

package.json, yarn.lock
Reverts trade-tariff/trade-tariff-admin#375
=> Revert "Bump chart.js from 4.1.1 to 4.1.2"

app/controllers/quotas_controller.rb, app/views/errors/not_found.html.erb, app/views/layouts/application.html.erb, spec/requests/quotas_controller_spec.rb
https://transformuk.atlassian.net/browse/HOTT-2226
- This is just for a nicer dev experience
=> HOTT-2226: Adds handling for quotas on xi

package.json, yarn.lock
HOTT-<TODO>
- To stay on top of CVEs
=> Bump yarn packages

app/models/tariff_update/inserts.rb, app/views/tariff_updates/show.html.erb, spec/factories/tariff_update_factory.rb, spec/models/tariff_update/inserts_spec.rb
https://transformuk.atlassian.net/browse/HOTT-2579
- We've removed this behaviour from the backend
=> HOTT-2579: Remove cascade destroys

.erb-lint.yml, app/views/references/chapters/search_references/edit.html.erb, app/views/references/chapters/search_references/index.html.erb, app/views/references/chapters/search_references/new.html.erb, app/views/references/commodities/search_references/edit.html.erb, app/views/references/commodities/search_references/index.html.erb, app/views/references/commodities/search_references/new.html.erb, app/views/references/headings/search_references/edit.html.erb, app/views/references/headings/search_references/index.html.erb, app/views/references/headings/search_references/new.html.erb, config/locales/en.yml, spec/features/chapter_search_reference_spec.rb, spec/features/commodity_search_reference_spec.rb, spec/features/heading_search_reference_spec.rb
https://transformuk.atlassian.net/browse/HOTT-2376
- This is a feature request before we extend the list of users of the admin UI
=> HOTT-2376: Adjust presentation of search reference table when no results

app/controllers/authenticated_controller.rb, app/controllers/news_items_controller.rb, app/views/application/_auth_banner.html.erb, lib/trade_tariff_admin/service_chooser.rb, spec/requests/news_items_controller_spec.rb
https://transformuk.atlassian.net/browse/HOTT-2664
- This makes no sense as all data is stored in uk
=> HOTT-2664: Disable service switching on news items

app/models/heading.rb, spec/factories/heading_factory.rb, spec/models/heading_spec.rb
https://transformuk.atlassian.net/browse/HOTT-2375
- This is a feature request from Matt
=> HOTT-2375: Adjust heading search reference title

.eslintrc.yml, app/models/quota_order_numbers/quota_definition.rb, app/views/quotas/_balance_events_chart.html.erb, app/webpacker/packs/quota-definition-chart.js, package.json, spec/models/quota_order_numbers/quota_definition_spec.rb, yarn.lock
https://transformuk.atlassian.net/browse/HOTT-2824
- This is required to help Matt more easily debug quotas
=> HOTT-2824: Overlay initial volumes and critical thresholds

app/controllers/rollbacks_controller.rb, app/controllers/tariff_updates_controller.rb, app/models/user.rb, app/policies/chapter_note_policy.rb, app/policies/news/collection_policy.rb, app/policies/news/item_policy.rb, app/policies/rollback_policy.rb, app/policies/search_reference_policy.rb, app/policies/section_note_policy.rb, app/policies/tariff_update_policy.rb, app/views/layouts/application.html.erb, spec/factories/user_factory.rb, spec/features/rollbacks_spec.rb, spec/features/tariff_updates_spec.rb, spec/models/user_spec.rb, spec/policies/chapter_note_policy_spec.rb, spec/policies/news/collection_policy_spec.rb, spec/policies/news/item_policy_spec.rb, spec/policies/rollback_policy_spec.rb, spec/policies/section_note_policy_spec.rb, spec/policies/tariff_update_policy_spec.rb, spec/requests/rollbacks_controller_spec.rb, spec/requests/tariff_updates_controller_spec.rb
https://transformuk.atlassian.net/browse/HOTT-1537
- We don't want to give full admin access to GDS and HMRC editors
=> HOTT-1537: Tiered admin rights

.circleci/config.yml, .pre-commit-config.yaml, app/controllers/healthcheck_controller.rb, config/routes.rb, spec/controllers/healthcheck_controller_spec.rb, terraform/.gitignore, terraform/.terraform.lock.hcl, terraform/README.md, terraform/backends/development.tfbackend, terraform/config_development.tfvars, terraform/data.tf, terraform/iam.tf, terraform/locals.tf, terraform/main.tf, terraform/variables.tf, terraform/versions.tf
[HOTT-3247](https://transformuk.atlassian.net/browse/HOTT-3247)
- Added Terraform to deploy service to AWS
- Added `/healthcheckz` endpoint for consistent container health checking akin to the other services
=> HOTT-3247: Create ECS Service

.circleci/config.yml, terraform/data.tf, terraform/iam.tf, terraform/locals.tf, terraform/main.tf
[HOTT-3247](https://transformuk.atlassian.net/browse/HOTT-3247)
- Updated the CircleCi config to deploy to ECS.
- Made changes where necessary to the Terraform.
- We have the Terraform but now need to deploy this through CI.
=> HOTT-3247: Deploy to ECS

package.json, yarn.lock
=> BAU: Bumps javascript deps

terraform/README.md, terraform/iam.tf, terraform/main.tf
- Bumped ECS service module to `v1.11.3`
- This module version has correctly implemented zero-downtime-deploys.
=> BAU: Zero Downtime Deploy

terraform/README.md, terraform/data.tf, terraform/iam.tf, terraform/main.tf
- Added postgres connection string
- We now have the separated admin DB
=> BAU: Add Postgres URL

terraform/main.tf
=> BAU: Enable ECS Exec

terraform/README.md, terraform/data.tf, terraform/iam.tf, terraform/locals.tf, terraform/main.tf
BAU
- This is required to get the admin apps working
=> BAU: Fixes admin configuration

terraform/config_development.tfvars, terraform/config_production.tfvars, terraform/config_staging.tfvars
BAU
- These were being terminated
=> BAU: Fixes resource constraints

app/controllers/tariff_updates_controller.rb, app/models/apply.rb, app/models/download.rb, app/views/tariff_updates/index.html.erb, config/routes.rb, spec/requests/tariff_updates_controller_spec.rb
https://transformuk.atlassian.net/browse/HOTT-4075
It calls the BE actions Download and Apply, 
by adding two HTTP buttons on the tariff_update index view.
To manually run the downloader and apply steps.
=> Add Download and Apply buttons

terraform/config_production.tfvars
BAU
- This is currently incorrect/pointing to the old test domain
=> BAU: Update base domain

app/controllers/tariff_updates_controller.rb, app/models/clear_cache.rb, app/views/tariff_updates/index.html.erb, config/routes.rb, spec/requests/tariff_updates_controller_spec.rb
https://transformuk.atlassian.net/browse/HOTT-4542
- This reduces our need to establish terminal sessions in the new env
=> HOTT-4542: Adds button to enable clearing the caches

.circleci/config.yml
[HOTT-4598](https://transformuk.atlassian.net/browse/HOTT-4598)
- Updated releases context in CircleCi config.
- We now have a new context that we can use for releases, so we'll want to use this.
=> HOTT-4598: Update CircleCi Contexts

Dockerfile, Makefile
https://transformuk.atlassian.net/browse/HOTT-4446
ECS healthchecks are managed separately:
https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_HealthCheck.html
- This is remediation work from our pentest report
=> HOTT-4446: Adds HEALTHCHECK

Gemfile.lock
BAU
- This was accidentally overwritten and required a reset
=> BAU: Bump routing-filter

.circleci/config.yml
- Release notes are failing in all deployments
=> BAU: Fix release notes job

.envrc, .gitignore, Gemfile, Gemfile.lock, app/models/green_lanes/update_notification.rb, flake.lock, flake.nix, gemset.nix
BAU
- This enables me to work on my machine
=> BAU: Enable nixos

.circleci/config.yml
BAU
- These were removed pending an investigation into dev/staging admin issues
=> BAU: Reinstate admin smoketests

.circleci/config.yml, .pre-commit-config.yaml, flake.nix, terraform/.terraform.lock.hcl, terraform/README.md, terraform/versions.tf
[HMRC-765](https://transformuk.atlassian.net/browse/HMRC-765)
- To get value out of these tests early
=> HMRC-765: Integrate e2e-tests github workflow

spec/requests/news_items_controller_spec.rb, terraform/README.md, terraform/config_development.tfvars, terraform/config_production.tfvars, terraform/config_staging.tfvars, terraform/data.tf, terraform/iam.tf, terraform/locals.tf, terraform/main.tf, terraform/variables.tf
[HMRC-868](https://transformuk.atlassian.net/browse/HMRC-868)
- This is part of the migration that I missed in review
=> HMRC-868: Replaces references to old secrets with new ones

Gemfile, Gemfile.lock, config/puma.rb
BAU
- We're actually using active record
=> BAU: Removes dead references to sequel

app/policies/chapter_note_policy.rb, app/policies/news/collection_policy.rb, app/policies/news/item_policy.rb, app/policies/search_reference_policy.rb, app/policies/section_note_policy.rb
=> BAU: Removes unused authorisation checks

.github/workflows/deploy-to-staging.yml
[HMRC-901](https://transformuk.atlassian.net/browse/HMRC-901)
I have a...
- exit 1 when the staging workflow outcome isn't success
I am doing this because...
- This will force the next workflow to fail
=> HMRC-901: Fixes staging workflow outcome

.github/workflows/deploy-to-development.yml, .github/workflows/deploy-to-production.yml, .github/workflows/deploy-to-staging.yml, .pre-commit-config.yaml
BAU
- Ref is worked out by the branch picked in the dispatch workflow and used
by the github action checkout action
=> BAU: Removes redundant ref

.github/workflows/deploy-to-development.yml, .github/workflows/deploy-to-production.yml
BAU
- This is noise not signal
=> BAU: Silence skipped production notifications

Gemfile.lock, yarn.lock
=> BAU: Bumps deps

.github/workflows/deploy-to-development-full.yml, .github/workflows/deploy-to-development.yml
[HMRC-1380](https://transformuk.atlassian.net/browse/HMRC-1380)
See https://github.com/trade-tariff/trade-tariff-tools/pull/61
- This enables us to validate a full e2e deployment in development
=> HMRC-1380: Adds deploy-full-stack job for proper e2e validation

Gemfile, Gemfile.lock, app/controllers/live_issues_controller.rb, app/helpers/live_issue_helper.rb, app/models/live_issue.rb, app/policies/live_issue_policy.rb, app/views/application/_markdown_field.html.erb, app/views/layouts/application.html.erb, app/views/live_issues/_form.html.erb, app/views/live_issues/edit.html.erb, app/views/live_issues/index.html.erb, app/views/live_issues/new.html.erb, app/views/notes/chapters/chapter_notes/_fields.html.erb, config/routes.rb, spec/factories/live_issue_factory.rb, spec/requests/live_issues_controller_spec.rb
=> HOS-8 | Add live issues management feature

.github/workflows/preview-up.yml
BAU
- We want to verify that the app is functional and the backend is connected.
- We want to receive an alert if the preview deployment fails or the e2e test does not pass.
=> Debug: preview e2e test fail
